#:schema node_modules/wrangler/config-schema.json
name = "vectyr-cloudflare"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "prod-vectyr"
database_id = "39d057cf-7e16-4a39-ba47-32295c33333d"

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "vector-index-vectyr"

[ai]
binding = "AI"

